# Generated by Django 4.1.3 on 2022-11-24 10:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0002_alter_customer_created_by"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Customers",
        ),
    ]
