# Generated by Django 4.1.3 on 2022-11-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_rename_customer_customers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customers",
        ),
    ]
