# Generated by Django 4.1.3 on 2022-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_initial"),
        ("order", "0003_remove_orderitem_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customers",
            field=models.ManyToManyField(
                related_name="orders", to="customers.customer"
            ),
        ),
    ]
