# Generated by Django 4.1.3 on 2022-11-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_initial"),
        ("order", "0005_remove_order_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="customer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="customers.customer",
            ),
            preserve_default=False,
        ),
    ]
